name: "google_calendar_project"
version: "1.0.0"
profile: "google_calendar_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  google_calendar_project:
    staging:
      +schema: DBT_STAGE
      +materialized: view

    intermediate:
      +schema: DBT_STAGE
      +materialized: view

    marts:
      +schema: DBT_STAGE
      +materialized: table
