version: 2

models:
  - name: calendar_events_summary
    description: "Aggregation for each event with the number of participants and breakdown by status"
    columns:
      - name: EVENT_ID
        description: "Unique event identifier"
        tests:
          - not_null
          - unique
      - name: EVENT_TITLE
        description: "Event name"
      - name: EVENT_START_AT
        description: "Event start date and time"
        tests:
          - not_null
      - name: total_attendees
        description: "Total number of unique event participants"

  - name: attendees_status_summary
    description: "Statistics for each participant: how many events, in which statuses participated"
    columns:
      - name: ATTENDEE_EMAIL
        description: "Participant's e-mail"
        tests:
          - not_null
          - unique
      - name: events_total
        description: "How many different events did this participant attend"
      - name: events_accepted
        description: "How many events did the participant accept"
      - name: events_declined
        description: "How many events did the participant decline"

  - name: events_activity_over_time
    description: "Activity by day and week: number of events and unique participants"
    columns:
      - name: activity_day
        description: "Day to which the activity refers"
        tests:
          - not_null
      - name: week_start
        description: "The beginning of the week to which this day belongs"
      - name: events_per_day
        description: "Number of events per day"
      - name: attendees_per_day
        description: "Number of unique participants per day"
